/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

/**
 *
 * @author DELL
 */
public class ejercicio4_cuadros_combinados extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio4_cuadros_combinados
     */
    public ejercicio4_cuadros_combinados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_resultado = new javax.swing.JLabel();
        combox_dias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eti_resultado.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        eti_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(eti_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 540, 60));

        combox_dias.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        combox_dias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo" }));
        combox_dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_diasActionPerformed(evt);
            }
        });
        getContentPane().add(combox_dias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("¿¿ Qué día es Hoy?? ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 310, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combox_diasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_diasActionPerformed
String mensaje="Hoy es... ";
 
mensaje=mensaje+combox_dias.getSelectedItem().toString();
eti_resultado.setText(mensaje);

    }//GEN-LAST:event_combox_diasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_cuadros_combinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_cuadros_combinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_cuadros_combinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio4_cuadros_combinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio4_cuadros_combinados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox_dias;
    private javax.swing.JLabel eti_resultado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
