/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class ejercicio5_modelo_cuadro_de_lista extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio5_modelo_cuadro_de_lista
     */
    public ejercicio5_modelo_cuadro_de_lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eti_resultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_conmebol = new javax.swing.JList<>();
        btn_clasificados = new javax.swing.JButton();
        btn_eliminados = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eti_resultado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        eti_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(eti_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 330, 50));

        lista_conmebol.setBackground(new java.awt.Color(204, 204, 204));
        lista_conmebol.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paises", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 24))); // NOI18N
        lista_conmebol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lista_conmebol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_conmebolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista_conmebol);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 220));

        btn_clasificados.setBackground(new java.awt.Color(204, 204, 204));
        btn_clasificados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_clasificados.setText("Clasificados");
        btn_clasificados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(102, 102, 102), new java.awt.Color(255, 0, 153), new java.awt.Color(255, 0, 255)));
        btn_clasificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clasificadosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clasificados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 130, 60));

        btn_eliminados.setBackground(new java.awt.Color(204, 204, 204));
        btn_eliminados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_eliminados.setText("Eliminados");
        btn_eliminados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 255), new java.awt.Color(153, 153, 153), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 0, 102)));
        btn_eliminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminadosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 130, 60));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ejerc_5.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 350, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clasificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clasificadosActionPerformed
    DefaultListModel modelo = new DefaultListModel();
modelo.addElement("Brasil");
modelo.addElement("Argentina");
modelo.addElement("Uruguay");
modelo.addElement("Ecuador");
lista_conmebol.setModel(modelo); 
    }//GEN-LAST:event_btn_clasificadosActionPerformed

    private void btn_eliminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminadosActionPerformed
    DefaultListModel modelo = new DefaultListModel();
modelo.addElement("Paraguay");
modelo.addElement("Chile");
modelo.addElement("Bolivia");
modelo.addElement("Venezuela");
modelo.addElement("Perú");
lista_conmebol.setModel(modelo); 
    }//GEN-LAST:event_btn_eliminadosActionPerformed

    private void lista_conmebolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_conmebolMouseClicked
eti_resultado.setText(lista_conmebol.getSelectedValue().toString());

    }//GEN-LAST:event_lista_conmebolMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio5_modelo_cuadro_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio5_modelo_cuadro_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio5_modelo_cuadro_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio5_modelo_cuadro_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio5_modelo_cuadro_de_lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clasificados;
    private javax.swing.JButton btn_eliminados;
    private javax.swing.JLabel eti_resultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista_conmebol;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
