/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

/**
 *
 * @author DELL
 */
public class ejercicio3_cuadros_de_lista extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio3_cuadros_de_lista
     */
    public ejercicio3_cuadros_de_lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abm_aceptar = new javax.swing.JButton();
        eti_resultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_animales = new javax.swing.JList<>();
        consulta = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abm_aceptar.setBackground(new java.awt.Color(153, 255, 255));
        abm_aceptar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        abm_aceptar.setText("ACEPTAR");
        abm_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abm_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(abm_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 330, 30));

        eti_resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eti_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(eti_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 520, 50));

        list_animales.setBackground(new java.awt.Color(204, 255, 255));
        list_animales.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        list_animales.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Tigre", "Perro", "Jirafa", "Mariposa" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_animales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 120));

        consulta.setBackground(new java.awt.Color(153, 255, 255));
        consulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consulta.setText(" SELECCIONA TU ANIMAL PREFERIDO");
        consulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 340, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ejerc_3.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 270, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abm_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abm_aceptarActionPerformed
String mensaje;
 
if (list_animales.getSelectedIndex()==-1) {
 mensaje="No seleccionaste ningun animal favorito...";
} else {
 mensaje="Tu animal favorito es: "+list_animales.getSelectedValue().toString();
}
eti_resultado.setText(mensaje);

    }//GEN-LAST:event_abm_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_cuadros_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_cuadros_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_cuadros_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio3_cuadros_de_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio3_cuadros_de_lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abm_aceptar;
    private javax.swing.JLabel consulta;
    private javax.swing.JLabel eti_resultado;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_animales;
    // End of variables declaration//GEN-END:variables
}
