/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class ejercicio6_combos_modelos extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio6_modelo_cuadro_de_lista
     */
    public ejercicio6_combos_modelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbo_numeros = new javax.swing.JComboBox<>();
        btn_par = new javax.swing.JButton();
        btn_impar = new javax.swing.JButton();
        etiq_result = new javax.swing.JLabel();
        imagen_icono = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbo_numeros.setBackground(new java.awt.Color(204, 204, 204));
        cbo_numeros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbo_numeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbo_numeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_numerosActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 180, 30));

        btn_par.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_par.setText("PARES");
        btn_par.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_par.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parActionPerformed(evt);
            }
        });
        getContentPane().add(btn_par, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 120, 50));

        btn_impar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_impar.setText("IMPARES");
        btn_impar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_impar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imparActionPerformed(evt);
            }
        });
        getContentPane().add(btn_impar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 120, 50));

        etiq_result.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiq_result.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        getContentPane().add(etiq_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 230, 50));

        imagen_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ejerc_6.jpg"))); // NOI18N
        imagen_icono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(imagen_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 290, 120));

        btn_limpiar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_parActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parActionPerformed
int i;

DefaultComboBoxModel modelo = new DefaultComboBoxModel();

for (i=0;i<11;i+=2) {
 modelo.addElement("Nº "+i);
}

cbo_numeros.setModel(modelo);
    }//GEN-LAST:event_btn_parActionPerformed

    private void btn_imparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imparActionPerformed
 int i;
DefaultComboBoxModel modelo = new DefaultComboBoxModel();

for (i=1;i<11;i+=2) {
 modelo.addElement("Nº "+i);
}

cbo_numeros.setModel(modelo);
    }//GEN-LAST:event_btn_imparActionPerformed

    private void cbo_numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_numerosActionPerformed
etiq_result.setText(" Seleccionaste el "+cbo_numeros.getSelectedItem().toString());
    }//GEN-LAST:event_cbo_numerosActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
DefaultComboBoxModel modelo = new DefaultComboBoxModel();
 modelo.addElement("");
 cbo_numeros.setModel(modelo);
 etiq_result.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio6_combos_modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio6_combos_modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio6_combos_modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio6_combos_modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio6_combos_modelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_impar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_par;
    private javax.swing.JComboBox<String> cbo_numeros;
    private javax.swing.JLabel etiq_result;
    private javax.swing.JLabel imagen_icono;
    // End of variables declaration//GEN-END:variables
}
