/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

/**
 *
 * @author DELL
 */
public class ejercicio2_botones_de_opcion extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio2_botones_de_opcion
     */
    public ejercicio2_botones_de_opcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_ciudades = new javax.swing.ButtonGroup();
        abm_aceptar = new javax.swing.JButton();
        eti_resultado = new javax.swing.JLabel();
        panel_ciudades = new javax.swing.JPanel();
        btn_asuncion = new javax.swing.JRadioButton();
        btn_capiata = new javax.swing.JRadioButton();
        btn_luque = new javax.swing.JRadioButton();
        consulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abm_aceptar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        abm_aceptar.setText("ACEPTAR");
        abm_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abm_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(abm_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 120, 40));

        eti_resultado.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        eti_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(eti_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 450, 50));

        panel_ciudades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Text", 3, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        grupo_ciudades.add(btn_asuncion);
        btn_asuncion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_asuncion.setSelected(true);
        btn_asuncion.setText("Asunción");
        btn_asuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asuncionActionPerformed(evt);
            }
        });

        grupo_ciudades.add(btn_capiata);
        btn_capiata.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_capiata.setText("Capiata");

        grupo_ciudades.add(btn_luque);
        btn_luque.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_luque.setText("Luque");

        javax.swing.GroupLayout panel_ciudadesLayout = new javax.swing.GroupLayout(panel_ciudades);
        panel_ciudades.setLayout(panel_ciudadesLayout);
        panel_ciudadesLayout.setHorizontalGroup(
            panel_ciudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ciudadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ciudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_asuncion, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(btn_capiata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_luque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        panel_ciudadesLayout.setVerticalGroup(
            panel_ciudadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ciudadesLayout.createSequentialGroup()
                .addComponent(btn_asuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btn_capiata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_luque, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(panel_ciudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 200, 150));

        consulta.setFont(new java.awt.Font("Consolas", 3, 16)); // NOI18N
        consulta.setText("En cual de las siguientes Ciudades te gustaria vivir?");
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abm_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abm_aceptarActionPerformed
String mensaje="La Ciudad seleccionada es: ";
 
 if (btn_asuncion.isSelected()) {
 mensaje=mensaje+"Asunción";
 } else if (btn_capiata.isSelected()) {
 mensaje=mensaje+"Capiata";
 } else if (btn_luque.isSelected()) {
 mensaje=mensaje+"Luque";
 }
 
 eti_resultado.setText(mensaje);
    }//GEN-LAST:event_abm_aceptarActionPerformed

    private void btn_asuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asuncionActionPerformed

    }//GEN-LAST:event_btn_asuncionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio2_botones_de_opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio2_botones_de_opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio2_botones_de_opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio2_botones_de_opcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio2_botones_de_opcion().setVisible(true);
            
   
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abm_aceptar;
    private javax.swing.JRadioButton btn_asuncion;
    private javax.swing.JRadioButton btn_capiata;
    private javax.swing.JRadioButton btn_luque;
    private javax.swing.JLabel consulta;
    private javax.swing.JLabel eti_resultado;
    private javax.swing.ButtonGroup grupo_ciudades;
    private javax.swing.JPanel panel_ciudades;
    // End of variables declaration//GEN-END:variables
}
