/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

/**
 *
 * @author DELL
 */
public class ejercicio10_scrollbars extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio10_scrollbars
     */
    public ejercicio10_scrollbars() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abm_scroll = new javax.swing.JScrollBar();
        etiq_resultado = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 260));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abm_scroll.setBlockIncrement(20);
        abm_scroll.setMaximum(155);
        abm_scroll.setMinimum(50);
        abm_scroll.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        abm_scroll.setUnitIncrement(2);
        abm_scroll.setVisibleAmount(5);
        abm_scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        abm_scroll.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                abm_scrollAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(abm_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 20));

        etiq_resultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiq_resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiq_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 40));

        titulo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        titulo.setText("BARRA DESPLAZADORA - SCROLLBARS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abm_scrollAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_abm_scrollAdjustmentValueChanged
    etiq_resultado.setText(" El valor es: "+abm_scroll.getValue());
    }//GEN-LAST:event_abm_scrollAdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio10_scrollbars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio10_scrollbars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio10_scrollbars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio10_scrollbars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio10_scrollbars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar abm_scroll;
    private javax.swing.JLabel etiq_resultado;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
