/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME1;

import javax.swing.*;
import java.awt.event.WindowEvent;

/**
 *
 * @author DELL
 */
public class ejercicio7_TOGGLEBUTTONS extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio7_TOGGLEBUTTONS
     */
    public ejercicio7_TOGGLEBUTTONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titulo_presupuesto = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        nombre_comercial = new javax.swing.JLabel();
        titulo_preciobase = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_preciobase = new javax.swing.JTextPane();
        etiq_total = new javax.swing.JLabel();
        btn_instalacion = new javax.swing.JToggleButton();
        btn_formacion = new javax.swing.JToggleButton();
        btn_BD = new javax.swing.JToggleButton();
        etiq_precioinstalacion = new javax.swing.JLabel();
        etiq_precioformacion = new javax.swing.JLabel();
        etiq_precioalimentacionBD = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        btns_salir = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(5, 57, 104));

        titulo_presupuesto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        titulo_presupuesto.setForeground(new java.awt.Color(255, 255, 255));
        titulo_presupuesto.setText("    PRESUPUESTO");

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/ejerc_7.jpg"))); // NOI18N
        icono.setText("jLabel1");

        nombre_comercial.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        nombre_comercial.setForeground(new java.awt.Color(255, 255, 255));
        nombre_comercial.setText("     WS - TECHNOLOGIES S.A");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titulo_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombre_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nombre_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo_preciobase.setBackground(new java.awt.Color(5, 57, 104));
        titulo_preciobase.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        titulo_preciobase.setText("     PRECIO BASE");

        txt_preciobase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_preciobase.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txt_preciobase);

        etiq_total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_instalacion.setBackground(new java.awt.Color(5, 57, 104));
        btn_instalacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_instalacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_instalacion.setText("Instalación");
        btn_instalacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_formacion.setBackground(new java.awt.Color(5, 57, 104));
        btn_formacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_formacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_formacion.setText("Formación");
        btn_formacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_formacion.setMaximumSize(new java.awt.Dimension(104, 26));
        btn_formacion.setMinimumSize(new java.awt.Dimension(104, 26));

        btn_BD.setBackground(new java.awt.Color(5, 57, 104));
        btn_BD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_BD.setForeground(new java.awt.Color(255, 255, 255));
        btn_BD.setText("Alimentación BD");
        btn_BD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        etiq_precioinstalacion.setText("400000");

        etiq_precioformacion.setText("2000000");

        etiq_precioalimentacionBD.setText("2500000");

        btn_calcular.setBackground(new java.awt.Color(5, 57, 104));
        btn_calcular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_calcular.setForeground(new java.awt.Color(255, 255, 255));
        btn_calcular.setText("CALCULAR");
        btn_calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        btns_salir.setBackground(new java.awt.Color(5, 57, 104));
        btns_salir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btns_salir.setForeground(new java.awt.Color(255, 255, 255));
        btns_salir.setText("SALIR");
        btns_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btns_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns_salirActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(5, 57, 104));
        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_formacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_BD))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiq_precioalimentacionBD)
                                    .addComponent(etiq_precioformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiq_precioinstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btns_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etiq_total, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titulo_preciobase, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_instalacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(130, 130, 130)
                                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(titulo_preciobase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(etiq_precioinstalacion))
                            .addComponent(btn_instalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_precioformacion)
                            .addComponent(btn_formacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_precioalimentacionBD))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(etiq_total, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btns_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
double precio_base;
double precio_instal; //precio instalación
double precio_for; //precio formacion
double precio_ali; //precio alimentacion

//Recojo datos desde la ventana:

precio_base = Double.parseDouble(txt_preciobase.getText());
precio_instal = Double.parseDouble(etiq_precioinstalacion.getText());
precio_for = Double.parseDouble(etiq_precioformacion.getText());
precio_ali = Double.parseDouble(etiq_precioalimentacionBD.getText());

//Ahora que tengo los datos, puedo hacer cálculos.

//Al precio base se le van añadiendo precio de extras
//según estén o no activados los JToggleButtons

double precio_total;

precio_total = precio_base;

if (btn_instalacion.isSelected()) { //Si se seleccionó instalación
 precio_total = precio_total+precio_instal;
}

if (btn_formacion.isSelected()) { //Si se seleccionó formación
 precio_total = precio_total+precio_for;
}

if (btn_BD.isSelected()) { //Si se seleccionó Alimentación BD
 precio_total = precio_total+precio_ali;
}


//Finalmente pongo el resultado en la etiqueta
etiq_total.setText(" El Presupuesto es de "+precio_total+" Gs.-");

        
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btns_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns_salirActionPerformed
    
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Salir",a);
       if (resultado == 0){      
        dispose();
       } 
    }//GEN-LAST:event_btns_salirActionPerformed
    
    
   private void windowsClosing(WindowEvent e){       
    dispose();
   }
    
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
 DefaultComboBoxModel modelo = new DefaultComboBoxModel();
 modelo.addElement("");
 etiq_total.setText("");
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio7_TOGGLEBUTTONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio7_TOGGLEBUTTONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio7_TOGGLEBUTTONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio7_TOGGLEBUTTONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio7_TOGGLEBUTTONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_BD;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JToggleButton btn_formacion;
    private javax.swing.JToggleButton btn_instalacion;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btns_salir;
    private javax.swing.JLabel etiq_precioalimentacionBD;
    private javax.swing.JLabel etiq_precioformacion;
    private javax.swing.JLabel etiq_precioinstalacion;
    private javax.swing.JLabel etiq_total;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre_comercial;
    private javax.swing.JLabel titulo_preciobase;
    private javax.swing.JLabel titulo_presupuesto;
    private javax.swing.JTextPane txt_preciobase;
    // End of variables declaration//GEN-END:variables
}
