/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME2;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class ejercicio12_barra_de_herramientas extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio12_barra_de_herramientas
     */
    public ejercicio12_barra_de_herramientas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barra_herramientas = new javax.swing.JToolBar();
        factura_ande = new javax.swing.JLabel();
        factura_essap = new javax.swing.JLabel();
        factura_tigo = new javax.swing.JLabel();
        diseño1 = new javax.swing.JPanel();
        diseño2 = new javax.swing.JPanel();
        marca1 = new javax.swing.JLabel();
        marca2 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        barra_menu = new javax.swing.JMenuBar();
        menu_pago = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 430));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 255));

        barra_herramientas.setRollover(true);

        factura_ande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo_ande_1.PNG"))); // NOI18N
        factura_ande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barra_herramientas.add(factura_ande);

        factura_essap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo_essap.PNG"))); // NOI18N
        factura_essap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barra_herramientas.add(factura_essap);

        factura_tigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo_tigo.PNG"))); // NOI18N
        factura_tigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        barra_herramientas.add(factura_tigo);

        diseño1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout diseño1Layout = new javax.swing.GroupLayout(diseño1);
        diseño1.setLayout(diseño1Layout);
        diseño1Layout.setHorizontalGroup(
            diseño1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        diseño1Layout.setVerticalGroup(
            diseño1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        diseño2.setBackground(new java.awt.Color(153, 153, 255));

        marca1.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        marca1.setForeground(new java.awt.Color(255, 255, 255));
        marca1.setText("PAGA=>PY ");

        marca2.setBackground(new java.awt.Color(255, 255, 255));
        marca2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        marca2.setForeground(new java.awt.Color(255, 255, 255));
        marca2.setText("RED DE PAGOS");

        javax.swing.GroupLayout diseño2Layout = new javax.swing.GroupLayout(diseño2);
        diseño2.setLayout(diseño2Layout);
        diseño2Layout.setHorizontalGroup(
            diseño2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diseño2Layout.createSequentialGroup()
                .addGroup(diseño2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diseño2Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(marca2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diseño2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(marca1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diseño2Layout.setVerticalGroup(
            diseño2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diseño2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marca2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_salir.setBackground(new java.awt.Color(153, 153, 255));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/salida.png"))); // NOI18N
        btn_salir.setText("SALIR");
        btn_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 102, 255), new java.awt.Color(153, 102, 255), new java.awt.Color(153, 102, 255), new java.awt.Color(153, 102, 255)));
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diseño1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diseño2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barra_herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barra_herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(diseño1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diseño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        menu_pago.setText("PAGO DE FACTURAS DE SERVICIOS");
        menu_pago.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        barra_menu.add(menu_pago);

        setJMenuBar(barra_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Salir",a);
       if (resultado == 0){
       System.exit(0);
       } 
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio12_barra_de_herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio12_barra_de_herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio12_barra_de_herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio12_barra_de_herramientas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio12_barra_de_herramientas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barra_herramientas;
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel diseño1;
    private javax.swing.JPanel diseño2;
    private javax.swing.JLabel factura_ande;
    private javax.swing.JLabel factura_essap;
    private javax.swing.JLabel factura_tigo;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel marca1;
    private javax.swing.JLabel marca2;
    private javax.swing.JMenu menu_pago;
    // End of variables declaration//GEN-END:variables
}
