/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME2;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author DELL
 */
public class ejercicio11_barra_menu extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio11_barra_menu
     */
    public ejercicio11_barra_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo1 = new javax.swing.JPanel();
        fondo2 = new javax.swing.JPanel();
        barra_menu = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        submenu_abrir = new javax.swing.JMenuItem();
        submenu_guardar = new javax.swing.JMenuItem();
        separador1 = new javax.swing.JPopupMenu.Separator();
        submenu_salir = new javax.swing.JMenuItem();
        menu_editar = new javax.swing.JMenu();
        menu_colores = new javax.swing.JMenu();
        submenu_rojo = new javax.swing.JMenuItem();
        submenu_verde = new javax.swing.JMenuItem();
        submenu_azul = new javax.swing.JMenuItem();
        menu_insertar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo1.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 650, -1));

        fondo2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout fondo2Layout = new javax.swing.GroupLayout(fondo2);
        fondo2.setLayout(fondo2Layout);
        fondo2Layout.setHorizontalGroup(
            fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        fondo2Layout.setVerticalGroup(
            fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 650, 110));

        menu_archivo.setBackground(new java.awt.Color(51, 153, 255));
        menu_archivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_archivo.setText("Archivo");
        menu_archivo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        submenu_abrir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/guardar.png"))); // NOI18N
        submenu_abrir.setText("Abrir");
        menu_archivo.add(submenu_abrir);

        submenu_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/Floppy.png"))); // NOI18N
        submenu_guardar.setText("Guardar");
        submenu_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(submenu_guardar);
        menu_archivo.add(separador1);

        submenu_salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/cerrar.png"))); // NOI18N
        submenu_salir.setText("Salir");
        submenu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(submenu_salir);

        barra_menu.add(menu_archivo);

        menu_editar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_editar.setText("Editar");
        menu_editar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        menu_colores.setText("Colores");
        menu_colores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        submenu_rojo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_rojo.setForeground(new java.awt.Color(255, 0, 51));
        submenu_rojo.setText("Rojo");
        submenu_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_rojoActionPerformed(evt);
            }
        });
        menu_colores.add(submenu_rojo);

        submenu_verde.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_verde.setForeground(new java.awt.Color(51, 204, 0));
        submenu_verde.setText("Verde");
        submenu_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_verdeActionPerformed(evt);
            }
        });
        menu_colores.add(submenu_verde);

        submenu_azul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submenu_azul.setForeground(new java.awt.Color(51, 0, 255));
        submenu_azul.setText("Azul");
        submenu_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_azulActionPerformed(evt);
            }
        });
        menu_colores.add(submenu_azul);

        menu_editar.add(menu_colores);

        barra_menu.add(menu_editar);

        menu_insertar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu_insertar.setText("Insertar");
        menu_insertar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        barra_menu.add(menu_insertar);

        setJMenuBar(barra_menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_rojoActionPerformed
    this.getContentPane().setBackground(Color.RED);
    }//GEN-LAST:event_submenu_rojoActionPerformed

    private void submenu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_salirActionPerformed
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Salir",a);
       if (resultado == 0){
       System.exit(0);
       } 
    }//GEN-LAST:event_submenu_salirActionPerformed

    private void submenu_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_guardarActionPerformed

    }//GEN-LAST:event_submenu_guardarActionPerformed

    private void submenu_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_verdeActionPerformed
    this.getContentPane().setBackground(Color.GREEN);
    }//GEN-LAST:event_submenu_verdeActionPerformed

    private void submenu_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_azulActionPerformed
    this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_submenu_azulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio11_barra_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio11_barra_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio11_barra_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio11_barra_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio11_barra_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JPanel fondo1;
    private javax.swing.JPanel fondo2;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_colores;
    private javax.swing.JMenu menu_editar;
    private javax.swing.JMenu menu_insertar;
    private javax.swing.JPopupMenu.Separator separador1;
    private javax.swing.JMenuItem submenu_abrir;
    private javax.swing.JMenuItem submenu_azul;
    private javax.swing.JMenuItem submenu_guardar;
    private javax.swing.JMenuItem submenu_rojo;
    private javax.swing.JMenuItem submenu_salir;
    private javax.swing.JMenuItem submenu_verde;
    // End of variables declaration//GEN-END:variables
}
