/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME2;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class ejercicio15_b_panel_de_desplazamiento extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio15_b_panel_de_desplazamiento
     */
    public ejercicio15_b_panel_de_desplazamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiq_titulo = new javax.swing.JLabel();
        scroll_datos = new javax.swing.JScrollPane();
        panel_datos = new javax.swing.JPanel();
        eti_panel_datos = new javax.swing.JLabel();
        etiq_tipo_dato = new javax.swing.JLabel();
        etiq_nombreBD = new javax.swing.JLabel();
        etiq_tabla = new javax.swing.JLabel();
        etiq_columna = new javax.swing.JLabel();
        etiq_clave = new javax.swing.JLabel();
        etiq_relacion = new javax.swing.JLabel();
        text_nombreBD = new javax.swing.JTextField();
        text_tabla = new javax.swing.JTextField();
        text_columna = new javax.swing.JTextField();
        text_clave = new javax.swing.JTextField();
        text_relacion = new javax.swing.JTextField();
        text_tipodato = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiq_titulo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiq_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/aceptar.png"))); // NOI18N
        etiq_titulo.setText("Ejemplo 2 de JScrollPane");
        getContentPane().add(etiq_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 30));

        panel_datos.setBackground(new java.awt.Color(0, 51, 255));

        eti_panel_datos.setFont(new java.awt.Font("Sitka Small", 3, 24)); // NOI18N
        eti_panel_datos.setForeground(new java.awt.Color(255, 255, 255));
        eti_panel_datos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/database_go.png"))); // NOI18N
        eti_panel_datos.setText("PANEL DE DATOS");

        etiq_tipo_dato.setBackground(new java.awt.Color(255, 255, 255));
        etiq_tipo_dato.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_tipo_dato.setForeground(new java.awt.Color(255, 255, 255));
        etiq_tipo_dato.setText("TIPO DE DATO");

        etiq_nombreBD.setBackground(new java.awt.Color(255, 255, 255));
        etiq_nombreBD.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_nombreBD.setForeground(new java.awt.Color(255, 255, 255));
        etiq_nombreBD.setText("NOMBRE DE BD");

        etiq_tabla.setBackground(new java.awt.Color(255, 255, 255));
        etiq_tabla.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_tabla.setForeground(new java.awt.Color(255, 255, 255));
        etiq_tabla.setText("TABLA");

        etiq_columna.setBackground(new java.awt.Color(255, 255, 255));
        etiq_columna.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_columna.setForeground(new java.awt.Color(255, 255, 255));
        etiq_columna.setText("COLUMNA");

        etiq_clave.setBackground(new java.awt.Color(255, 255, 255));
        etiq_clave.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_clave.setForeground(new java.awt.Color(255, 255, 255));
        etiq_clave.setText("CLAVE");

        etiq_relacion.setBackground(new java.awt.Color(255, 255, 255));
        etiq_relacion.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        etiq_relacion.setForeground(new java.awt.Color(255, 255, 255));
        etiq_relacion.setText("RELACION");

        text_nombreBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nombreBDActionPerformed(evt);
            }
        });

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/Floppy.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/salida.png"))); // NOI18N
        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_datosLayout = new javax.swing.GroupLayout(panel_datos);
        panel_datos.setLayout(panel_datosLayout);
        panel_datosLayout.setHorizontalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addComponent(eti_panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(panel_datosLayout.createSequentialGroup()
                        .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_relacion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_tipo_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 83, Short.MAX_VALUE)
                        .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(text_nombreBD, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(text_tabla))
                            .addComponent(text_columna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_clave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_relacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_tipodato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(75, Short.MAX_VALUE))))
            .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(etiq_nombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );
        panel_datosLayout.setVerticalGroup(
            panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_panel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(text_nombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_columna, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiq_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_relacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_relacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiq_tipo_dato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tipodato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(panel_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosLayout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(etiq_nombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        scroll_datos.setViewportView(panel_datos);

        getContentPane().add(scroll_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nombreBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nombreBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nombreBDActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Salir",a);
       if (resultado == 0){
       System.exit(0);
       }
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio15_b_panel_de_desplazamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio15_b_panel_de_desplazamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio15_b_panel_de_desplazamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio15_b_panel_de_desplazamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio15_b_panel_de_desplazamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel eti_panel_datos;
    private javax.swing.JLabel etiq_clave;
    private javax.swing.JLabel etiq_columna;
    private javax.swing.JLabel etiq_nombreBD;
    private javax.swing.JLabel etiq_relacion;
    private javax.swing.JLabel etiq_tabla;
    private javax.swing.JLabel etiq_tipo_dato;
    private javax.swing.JLabel etiq_titulo;
    private javax.swing.JPanel panel_datos;
    private javax.swing.JScrollPane scroll_datos;
    private javax.swing.JTextField text_clave;
    private javax.swing.JTextField text_columna;
    private javax.swing.JTextField text_nombreBD;
    private javax.swing.JTextField text_relacion;
    private javax.swing.JTextField text_tabla;
    private javax.swing.JTextField text_tipodato;
    // End of variables declaration//GEN-END:variables
}
