/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFRAME2;

/**
 *
 * @author DELL
 */
public class ejercicio20_dialogos extends javax.swing.JFrame {
double iva;
double descuento;
    /**
     * Creates new form ejercicio20_dialogos
     */
    public ejercicio20_dialogos() {
        initComponents();
        iva=0;
        descuento=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogo_configuracion = new javax.swing.JDialog();
        panel_fondo_dialogo = new javax.swing.JPanel();
        eti_iva = new javax.swing.JLabel();
        eti_descto = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel_fondo = new javax.swing.JPanel();
        eti_unid = new javax.swing.JLabel();
        eti_precio = new javax.swing.JLabel();
        txt_unidades = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        eti_nombretotal = new javax.swing.JLabel();
        etiq_total = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();

        dialogo_configuracion.setTitle("Configuración de IVA y Descuento");
        dialogo_configuracion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        dialogo_configuracion.setResizable(false);

        panel_fondo_dialogo.setBackground(new java.awt.Color(51, 204, 255));

        eti_iva.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eti_iva.setForeground(new java.awt.Color(255, 255, 255));
        eti_iva.setText("IVA %");

        eti_descto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eti_descto.setForeground(new java.awt.Color(255, 255, 255));
        eti_descto.setText("DESCUENTO %");

        txt_iva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_descuento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btn_aceptar.setBackground(new java.awt.Color(51, 153, 255));
        btn_aceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(51, 153, 255));
        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondo_dialogoLayout = new javax.swing.GroupLayout(panel_fondo_dialogo);
        panel_fondo_dialogo.setLayout(panel_fondo_dialogoLayout);
        panel_fondo_dialogoLayout.setHorizontalGroup(
            panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondo_dialogoLayout.createSequentialGroup()
                .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fondo_dialogoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eti_descto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_iva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_iva)
                            .addComponent(txt_descuento, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addGroup(panel_fondo_dialogoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        panel_fondo_dialogoLayout.setVerticalGroup(
            panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondo_dialogoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_iva)
                    .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_descto)
                    .addComponent(txt_descuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panel_fondo_dialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout dialogo_configuracionLayout = new javax.swing.GroupLayout(dialogo_configuracion.getContentPane());
        dialogo_configuracion.getContentPane().setLayout(dialogo_configuracionLayout);
        dialogo_configuracionLayout.setHorizontalGroup(
            dialogo_configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_configuracionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panel_fondo_dialogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        dialogo_configuracionLayout.setVerticalGroup(
            dialogo_configuracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogo_configuracionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel_fondo_dialogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        panel_fondo.setBackground(new java.awt.Color(51, 204, 255));

        eti_unid.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eti_unid.setForeground(new java.awt.Color(255, 255, 255));
        eti_unid.setText("UNIDADES:");

        eti_precio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eti_precio.setForeground(new java.awt.Color(255, 255, 255));
        eti_precio.setText("PRECIO:");

        txt_unidades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txt_precio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        eti_nombretotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eti_nombretotal.setForeground(new java.awt.Color(255, 255, 255));
        eti_nombretotal.setText("TOTAL:");

        etiq_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiq_total.setForeground(new java.awt.Color(255, 255, 255));
        etiq_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_calcular.setBackground(new java.awt.Color(51, 153, 255));
        btn_calcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_calcular.setForeground(new java.awt.Color(255, 255, 255));
        btn_calcular.setText("CALCULAR");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        btn_configuracion.setBackground(new java.awt.Color(51, 153, 255));
        btn_configuracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_configuracion.setForeground(new java.awt.Color(255, 255, 255));
        btn_configuracion.setText("CONFIGURACIÓN");
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eti_nombretotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_unid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_unidades)
                                .addComponent(txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                            .addComponent(etiq_total, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(44, 44, 44))))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_unid)
                    .addComponent(txt_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_precio)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eti_nombretotal)
                    .addComponent(etiq_total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panel_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed

double unidades;
double precio;
double total;
double cantiva;
double cantdes;
double totalsiniva;

unidades = Double.parseDouble(txt_unidades.getText());
precio = Double.parseDouble(txt_precio.getText());
 
totalsiniva=precio*unidades;
cantiva=totalsiniva*iva/100;
cantdes=totalsiniva*descuento/100;

total = totalsiniva+cantiva-cantdes;
etiq_total.setText(""+total);

    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
iva = Double.parseDouble(txt_iva.getText());
descuento=Double.parseDouble(txt_descuento.getText());
dialogo_configuracion.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
dialogo_configuracion.setSize(490,400);
dialogo_configuracion.setLocation(100,100);
dialogo_configuracion.setVisible(true);

    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
    dialogo_configuracion.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio20_dialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio20_dialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio20_dialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio20_dialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio20_dialogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JDialog dialogo_configuracion;
    private javax.swing.JLabel eti_descto;
    private javax.swing.JLabel eti_iva;
    private javax.swing.JLabel eti_nombretotal;
    private javax.swing.JLabel eti_precio;
    private javax.swing.JLabel eti_unid;
    private javax.swing.JLabel etiq_total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel panel_fondo_dialogo;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_unidades;
    // End of variables declaration//GEN-END:variables
}
