/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import JFRAME1.*;
import JFRAME2.*;
import referenciales.ciudad;
import referenciales.inscripcion;

import javax.swing.*;

/**
 *
 * @author DELL
 */
public class menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public menu_principal() {
        initComponents();
        this.setExtendedState (MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        submenu_cerrarsesion = new javax.swing.JMenuItem();
        submenu_salir = new javax.swing.JMenuItem();
        menu_jframe1 = new javax.swing.JMenu();
        submenu_ejerc1 = new javax.swing.JMenuItem();
        submenu_ejerc2 = new javax.swing.JMenuItem();
        submenu_ejerc3 = new javax.swing.JMenuItem();
        submenu_ejerc4 = new javax.swing.JMenuItem();
        submenu_ejerc5 = new javax.swing.JMenuItem();
        submenu_ejerc6 = new javax.swing.JMenuItem();
        submenu_ejerc7 = new javax.swing.JMenuItem();
        submenu_ejerc8 = new javax.swing.JMenuItem();
        submenu_ejerc9 = new javax.swing.JMenuItem();
        submenu_ejerc10 = new javax.swing.JMenuItem();
        menu_jframe2 = new javax.swing.JMenu();
        submenu_ejerc11 = new javax.swing.JMenuItem();
        submenu_ejerc12 = new javax.swing.JMenuItem();
        submenu_ejerc13 = new javax.swing.JMenuItem();
        submenu_ejerc14 = new javax.swing.JMenuItem();
        submenu_ejerc15_1 = new javax.swing.JMenuItem();
        submenu_ejerc15_2 = new javax.swing.JMenuItem();
        submenu_ejerc16 = new javax.swing.JMenuItem();
        submenu_ejerc17 = new javax.swing.JMenuItem();
        submenu_ejerc18 = new javax.swing.JMenuItem();
        submenu_ejerc19 = new javax.swing.JMenuItem();
        submenu_ejerc20 = new javax.swing.JMenuItem();
        menu_referenciales = new javax.swing.JMenu();
        submenu_ciudad = new javax.swing.JMenuItem();
        submenu_pais = new javax.swing.JMenuItem();
        submenu_inscripcion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/imagen_menu.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        getContentPane().add(jcMousePanel1, java.awt.BorderLayout.CENTER);

        menu_archivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/Floppy.png"))); // NOI18N
        menu_archivo.setText("ARCHIVO");
        menu_archivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_archivo.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N

        submenu_cerrarsesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/cerrar.png"))); // NOI18N
        submenu_cerrarsesion.setText("CERRAR SESIÓN");
        submenu_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_cerrarsesionActionPerformed(evt);
            }
        });
        menu_archivo.add(submenu_cerrarsesion);

        submenu_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/exit.png"))); // NOI18N
        submenu_salir.setText("SALIR");
        submenu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(submenu_salir);

        jMenuBar1.add(menu_archivo);

        menu_jframe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icon_java.png"))); // NOI18N
        menu_jframe1.setText("EJERCICIOS JFRAME_1");
        menu_jframe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_jframe1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N

        submenu_ejerc1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc1.setText("Jframe1 - Cuadros De Verificación");
        submenu_ejerc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc1ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc1);

        submenu_ejerc2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc2.setText("Jframe2 - Botones De Opción");
        submenu_ejerc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc2ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc2);

        submenu_ejerc3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc3.setText("Jframe3 - Cuadros De Lista");
        submenu_ejerc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc3ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc3);

        submenu_ejerc4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc4.setText("Jframe4 - Cuadros Combinados");
        submenu_ejerc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc4ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc4);

        submenu_ejerc5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc5.setText("Jframe5 - Modelos De Cuadro De Lista 1");
        submenu_ejerc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc5ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc5);

        submenu_ejerc6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc6.setText("Jframe6 - Modelos De Cuadro De Lista 2");
        submenu_ejerc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc6ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc6);

        submenu_ejerc7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc7.setText("Jframe7 – Togglebuttons");
        submenu_ejerc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc7ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc7);

        submenu_ejerc8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc8.setText("Jframe8 – Sliders");
        submenu_ejerc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc8ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc8);

        submenu_ejerc9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc9.setText("Jframe9 – Spinner");
        submenu_ejerc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc9ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc9);

        submenu_ejerc10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc10.setText("Jframe10 – Scrollbars");
        submenu_ejerc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc10ActionPerformed(evt);
            }
        });
        menu_jframe1.add(submenu_ejerc10);

        jMenuBar1.add(menu_jframe1);

        menu_jframe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/icon_java.png"))); // NOI18N
        menu_jframe2.setText("EJERCICIOS JFRAME_2");
        menu_jframe2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_jframe2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N

        submenu_ejerc11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc11.setText("Jframe11 - Barra De Menus");
        submenu_ejerc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc11ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc11);

        submenu_ejerc12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc12.setText("Jframe12 - Barra De Herramientas");
        submenu_ejerc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc12ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc12);

        submenu_ejerc13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc13.setText("Jframe13 - Menus Emergentes");
        submenu_ejerc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc13ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc13);

        submenu_ejerc14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc14.setText("Jframe14 – Filechooser");
        submenu_ejerc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc14ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc14);

        submenu_ejerc15_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc15_1.setText("Jframe15 - Paneles De Desplazamiento_1");
        submenu_ejerc15_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc15_1ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc15_1);

        submenu_ejerc15_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc15_2.setText("Jframe15 - Paneles De Desplazamiento_2");
        submenu_ejerc15_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc15_2ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc15_2);

        submenu_ejerc16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc16.setText("Jframe16 - Variables Globales");
        submenu_ejerc16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc16ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc16);

        submenu_ejerc17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc17.setText("Jframe17 - Centralizar Código");
        submenu_ejerc17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc17ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc17);

        submenu_ejerc18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc18.setText("Jframe18 – Layouts");
        submenu_ejerc18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc18ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc18);

        submenu_ejerc19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc19.setText("Jframe19 - Layouts Y Paneles");
        submenu_ejerc19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc19ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc19);

        submenu_ejerc20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ejerc20.setText("Jframe20 - Diálogos");
        submenu_ejerc20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ejerc20ActionPerformed(evt);
            }
        });
        menu_jframe2.add(submenu_ejerc20);

        jMenuBar1.add(menu_jframe2);

        menu_referenciales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/database_go.png"))); // NOI18N
        menu_referenciales.setText("REFERENCIALES");
        menu_referenciales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_referenciales.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N

        submenu_ciudad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_ciudad.setText("Formulario CIUDAD");
        submenu_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_ciudadActionPerformed(evt);
            }
        });
        menu_referenciales.add(submenu_ciudad);

        submenu_pais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_pais.setText("Formulario PAIS");
        menu_referenciales.add(submenu_pais);

        submenu_inscripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submenu_inscripcion.setText("Formulario Inscripción");
        submenu_inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_inscripcionActionPerformed(evt);
            }
        });
        menu_referenciales.add(submenu_inscripcion);

        jMenuBar1.add(menu_referenciales);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_ejerc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc1ActionPerformed
new ejercicio1_cuadros_verificacion().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc1ActionPerformed

    private void submenu_ejerc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc2ActionPerformed
new ejercicio2_botones_de_opcion().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc2ActionPerformed

    private void submenu_ejerc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc3ActionPerformed
new ejercicio3_cuadros_de_lista().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc3ActionPerformed

    private void submenu_ejerc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc4ActionPerformed
new ejercicio4_cuadros_combinados().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc4ActionPerformed

    private void submenu_ejerc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc5ActionPerformed
new ejercicio5_modelo_cuadro_de_lista().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc5ActionPerformed

    private void submenu_ejerc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc6ActionPerformed
new ejercicio6_combos_modelos().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc6ActionPerformed

    private void submenu_ejerc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc7ActionPerformed
new ejercicio7_TOGGLEBUTTONS().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc7ActionPerformed

    private void submenu_ejerc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc8ActionPerformed
new ejercicio8_sliders().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc8ActionPerformed

    private void submenu_ejerc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc9ActionPerformed
new ejercicio9_spinner().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc9ActionPerformed

    private void submenu_ejerc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc10ActionPerformed
new ejercicio10_scrollbars().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc10ActionPerformed

    private void submenu_ejerc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc11ActionPerformed
new ejercicio11_barra_menu().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc11ActionPerformed

    private void submenu_ejerc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc12ActionPerformed
new ejercicio12_barra_de_herramientas().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc12ActionPerformed

    private void submenu_ejerc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc13ActionPerformed
new ejercicio13_menu_emergente().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc13ActionPerformed

    private void submenu_ejerc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc14ActionPerformed
new ejercicio14_filechooser().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc14ActionPerformed

    private void submenu_ejerc15_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc15_1ActionPerformed
new ejercicio15_a_panel_de_desplazamiento().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc15_1ActionPerformed

    private void submenu_ejerc15_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc15_2ActionPerformed
new ejercicio15_b_panel_de_desplazamiento().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc15_2ActionPerformed

    private void submenu_ejerc16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc16ActionPerformed
 new ejercicio16_variables_globales().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc16ActionPerformed

    private void submenu_ejerc17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc17ActionPerformed
new ejercicio17_centralizar_codigo().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc17ActionPerformed

    private void submenu_ejerc18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc18ActionPerformed
new ejercicio18_layouts().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc18ActionPerformed

    private void submenu_ejerc19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc19ActionPerformed
new ejercicio19_layouts_y_paneles().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc19ActionPerformed

    private void submenu_ejerc20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ejerc20ActionPerformed
new ejercicio20_dialogos().setVisible(true);
    }//GEN-LAST:event_submenu_ejerc20ActionPerformed

    private void submenu_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_ciudadActionPerformed
new ciudad().setVisible(true);
    }//GEN-LAST:event_submenu_ciudadActionPerformed

    private void submenu_inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_inscripcionActionPerformed
new inscripcion().setVisible(true);
    }//GEN-LAST:event_submenu_inscripcionActionPerformed

    private void submenu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_salirActionPerformed
       int a = JOptionPane.YES_NO_OPTION;
       int resultado = JOptionPane.showConfirmDialog(this,"¿Desea Salir?","Salir",a);
       if (resultado == 0){
       System.exit(0);
       } 
    }//GEN-LAST:event_submenu_salirActionPerformed

    private void submenu_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_cerrarsesionActionPerformed
   
        new acceso().setVisible(true);
        
    }//GEN-LAST:event_submenu_cerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenu menu_jframe1;
    private javax.swing.JMenu menu_jframe2;
    private javax.swing.JMenu menu_referenciales;
    private javax.swing.JMenuItem submenu_cerrarsesion;
    private javax.swing.JMenuItem submenu_ciudad;
    private javax.swing.JMenuItem submenu_ejerc1;
    private javax.swing.JMenuItem submenu_ejerc10;
    private javax.swing.JMenuItem submenu_ejerc11;
    private javax.swing.JMenuItem submenu_ejerc12;
    private javax.swing.JMenuItem submenu_ejerc13;
    private javax.swing.JMenuItem submenu_ejerc14;
    private javax.swing.JMenuItem submenu_ejerc15_1;
    private javax.swing.JMenuItem submenu_ejerc15_2;
    private javax.swing.JMenuItem submenu_ejerc16;
    private javax.swing.JMenuItem submenu_ejerc17;
    private javax.swing.JMenuItem submenu_ejerc18;
    private javax.swing.JMenuItem submenu_ejerc19;
    private javax.swing.JMenuItem submenu_ejerc2;
    private javax.swing.JMenuItem submenu_ejerc20;
    private javax.swing.JMenuItem submenu_ejerc3;
    private javax.swing.JMenuItem submenu_ejerc4;
    private javax.swing.JMenuItem submenu_ejerc5;
    private javax.swing.JMenuItem submenu_ejerc6;
    private javax.swing.JMenuItem submenu_ejerc7;
    private javax.swing.JMenuItem submenu_ejerc8;
    private javax.swing.JMenuItem submenu_ejerc9;
    private javax.swing.JMenuItem submenu_inscripcion;
    private javax.swing.JMenuItem submenu_pais;
    private javax.swing.JMenuItem submenu_salir;
    // End of variables declaration//GEN-END:variables

 
 


}
