/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package referenciales;

import login.menu_principal;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;

/**
 *
 * @author DELL
 */
public class inscripcion extends javax.swing.JFrame {
String variable_accion="";


    /**
     * Creates new form inscripcion
     */
    public inscripcion() {
        initComponents();
        this.setSize(947,670);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        jcmouse_logo = new jcMousePanel.jcMousePanel();
        panel_titulo = new javax.swing.JPanel();
        etiq_titulo = new javax.swing.JLabel();
        etiq_codigo = new javax.swing.JLabel();
        etiq_nombre = new javax.swing.JLabel();
        etiq_apellido = new javax.swing.JLabel();
        etiq_cedula = new javax.swing.JLabel();
        etiq_telefono = new javax.swing.JLabel();
        etiq_direccion = new javax.swing.JLabel();
        etiq_ciudad = new javax.swing.JLabel();
        etiq_pais = new javax.swing.JLabel();
        etiq_estado = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        cbox_ciudad = new javax.swing.JComboBox<>();
        cbox_pais = new javax.swing.JComboBox<>();
        rabtn_estado = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_contenido = new javax.swing.JTable();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_grabar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.setBackground(new java.awt.Color(107, 142, 165));
        panel_fondo.setPreferredSize(new java.awt.Dimension(950, 700));

        jcmouse_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/imagen_formulario.png"))); // NOI18N
        jcmouse_logo.setVisibleLogo(false);

        javax.swing.GroupLayout jcmouse_logoLayout = new javax.swing.GroupLayout(jcmouse_logo);
        jcmouse_logo.setLayout(jcmouse_logoLayout);
        jcmouse_logoLayout.setHorizontalGroup(
            jcmouse_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jcmouse_logoLayout.setVerticalGroup(
            jcmouse_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        panel_titulo.setBackground(new java.awt.Color(98, 131, 153));
        panel_titulo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEtchedBorder()));

        etiq_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etiq_titulo.setForeground(new java.awt.Color(255, 255, 255));
        etiq_titulo.setText("FORMULARIO DE INSCRIPCIÓN");

        javax.swing.GroupLayout panel_tituloLayout = new javax.swing.GroupLayout(panel_titulo);
        panel_titulo.setLayout(panel_tituloLayout);
        panel_tituloLayout.setHorizontalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiq_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tituloLayout.setVerticalGroup(
            panel_tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(etiq_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        etiq_codigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_codigo.setForeground(new java.awt.Color(255, 255, 255));
        etiq_codigo.setText("CÓDIGO:");

        etiq_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_nombre.setForeground(new java.awt.Color(255, 255, 255));
        etiq_nombre.setText("NOMBRE:");

        etiq_apellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_apellido.setForeground(new java.awt.Color(255, 255, 255));
        etiq_apellido.setText("APELLIDO:");

        etiq_cedula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_cedula.setForeground(new java.awt.Color(255, 255, 255));
        etiq_cedula.setText("CÉDULA:");

        etiq_telefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_telefono.setForeground(new java.awt.Color(255, 255, 255));
        etiq_telefono.setText("TELÉFONO:");

        etiq_direccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_direccion.setForeground(new java.awt.Color(255, 255, 255));
        etiq_direccion.setText("DIRECCIÓN:");

        etiq_ciudad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_ciudad.setForeground(new java.awt.Color(255, 255, 255));
        etiq_ciudad.setText("CIUDAD:");

        etiq_pais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_pais.setForeground(new java.awt.Color(255, 255, 255));
        etiq_pais.setText("PAÍS:");

        etiq_estado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiq_estado.setForeground(new java.awt.Color(255, 255, 255));
        etiq_estado.setText("ESTADO:");

        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoKeyTyped(evt);
            }
        });

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyPressed(evt);
            }
        });

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_direccionKeyPressed(evt);
            }
        });

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });

        cbox_ciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbox_ciudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asunción", "Areguá", "Capiatá", "Fernando de la Mora", "Guarambaré", "Itá", "Itauguá", "J. Augusto Saldívar", "Lambaré", "Limpio", "Luque", "Mariano Roque Alonso", "Ñemby", "Nueva Italia", "San Antonio", "San Lorenzo", "Villa Elisa", "Villeta", "Ypacarai", "Ypané" }));
        cbox_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbox_ciudadKeyPressed(evt);
            }
        });

        cbox_pais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbox_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paraguay", "Argentina", "Brasil", "Chile", "Bolivia", "Ecuador", "Colombia", "Uruguay", "Peru", "EE.UU", "Mexico" }));
        cbox_pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbox_paisKeyPressed(evt);
            }
        });

        rabtn_estado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rabtn_estado.setForeground(new java.awt.Color(255, 255, 255));
        rabtn_estado.setSelected(true);
        rabtn_estado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rabtn_estado.setOpaque(true);
        rabtn_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rabtn_estadoKeyPressed(evt);
            }
        });

        tabla_contenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRE", "APELLIDO", "CÉDULA", "DIRECCIÓN", "TELÉFONO", "CIUDAD", "PAÍS", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_contenido.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla_contenido);
        if (tabla_contenido.getColumnModel().getColumnCount() > 0) {
            tabla_contenido.getColumnModel().getColumn(0).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(1).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(2).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(3).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(4).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(5).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(6).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(7).setResizable(false);
            tabla_contenido.getColumnModel().getColumn(8).setResizable(false);
        }

        btn_nuevo.setBackground(new java.awt.Color(68, 90, 105));
        btn_nuevo.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("NUEVO");
        btn_nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_modificar.setBackground(new java.awt.Color(68, 90, 105));
        btn_modificar.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar.setText("MODIFICAR");
        btn_modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(68, 90, 105));
        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_grabar.setBackground(new java.awt.Color(68, 90, 105));
        btn_grabar.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_grabar.setForeground(new java.awt.Color(255, 255, 255));
        btn_grabar.setText("GRABAR");
        btn_grabar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(68, 90, 105));
        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(68, 90, 105));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 3, 19)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("SALIR");
        btn_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176), new java.awt.Color(114, 152, 176)));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_fondoLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(txt_cedula)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_apellido)
                                    .addComponent(txt_codigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiq_telefono)
                                    .addComponent(etiq_ciudad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiq_pais, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiq_estado, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_fondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmouse_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_fondoLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_telefono)
                                    .addComponent(cbox_ciudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbox_pais, 0, 209, Short.MAX_VALUE)
                                    .addComponent(rabtn_estado))))
                        .addGap(16, 16, 16))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_fondoLayout.createSequentialGroup()
                                .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btn_modificar)
                                .addGap(43, 43, 43)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btn_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(etiq_direccion)
                                .addComponent(etiq_nombre)
                                .addComponent(etiq_codigo)
                                .addComponent(etiq_apellido)
                                .addComponent(etiq_cedula)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcmouse_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_codigo)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_apellido))
                        .addGap(11, 11, 11)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_cedula)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiq_direccion)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_fondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_telefono)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiq_ciudad)
                            .addComponent(cbox_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbox_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiq_pais))
                        .addGap(9, 9, 9)
                        .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiq_estado)
                            .addComponent(rabtn_estado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(panel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
variable_accion="modificar";
if(txt_codigo.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"DEBES SELECCIONAR UN REGISTRO","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
        deshabilitar_botones();


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
    //limpiar siempre los campos
   
    deshabilitar_botones();
    variable_accion="Nuevo";
    txt_codigo.setEnabled(true);
    txt_codigo.requestFocus();
 
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void txt_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyTyped
    if (Character.isDigit(evt.getKeyChar()) == false){
    evt.consume();
    }
        
    }//GEN-LAST:event_txt_codigoKeyTyped

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_apellido.setEnabled(true);
    txt_apellido.requestFocus();
        }
    }//GEN-LAST:event_txt_nombreKeyPressed

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_nombre.setEnabled(true);
    txt_nombre.requestFocus();
        }
    }//GEN-LAST:event_txt_codigoKeyPressed

    private void txt_apellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_cedula.setEnabled(true);
    txt_cedula.requestFocus();
        }
    }//GEN-LAST:event_txt_apellidoKeyPressed

    private void txt_cedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_direccion.setEnabled(true);
    txt_direccion.requestFocus();
        }
    }//GEN-LAST:event_txt_cedulaKeyPressed

    private void txt_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    txt_telefono.setEnabled(true);
    txt_telefono.requestFocus();
        }
    }//GEN-LAST:event_txt_direccionKeyPressed

    private void txt_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    cbox_ciudad.setEnabled(true);
    cbox_ciudad.requestFocus();
        }
    }//GEN-LAST:event_txt_telefonoKeyPressed

    private void cbox_ciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbox_ciudadKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    cbox_pais.setEnabled(true);
    cbox_pais.requestFocus();
        }
    }//GEN-LAST:event_cbox_ciudadKeyPressed

    private void cbox_paisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbox_paisKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    rabtn_estado.setEnabled(true);
    rabtn_estado.requestFocus();
        }
    }//GEN-LAST:event_cbox_paisKeyPressed

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
    if (Character.isDigit(evt.getKeyChar()) == false){
    evt.consume();
    }
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
    if (Character.isDigit(evt.getKeyChar()) == false){
    evt.consume();
    }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void rabtn_estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rabtn_estadoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER){
    btn_grabar.doClick();
        }
    }//GEN-LAST:event_rabtn_estadoKeyPressed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
txt_codigo.setText("");
txt_nombre.setText("");
txt_apellido.setText("");
txt_cedula.setText("");
txt_direccion.setText("");
txt_telefono.setText("");
cbox_ciudad.setSelectedIndex(0);
cbox_pais.setSelectedIndex(0);
rabtn_estado.setSelected(true);

txt_codigo.setEnabled(false);
txt_nombre.setEnabled(false);
txt_apellido.setEnabled(false);
txt_cedula.setEnabled(false);
txt_direccion.setEnabled(false);
txt_telefono.setEnabled(false);
cbox_ciudad.setEnabled(false);
cbox_pais.setEnabled(false);
rabtn_estado.setEnabled(false);
        

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabarActionPerformed
    if (txt_codigo.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar el Código", "Error", JOptionPane.ERROR_MESSAGE);
    txt_codigo.requestFocus();
    return;
       }
    
    if (txt_nombre.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar el Nombre", "Error", JOptionPane.ERROR_MESSAGE);
    txt_nombre.requestFocus();
    return;
       }
    
    if (txt_apellido.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar el Apellido", "Error", JOptionPane.ERROR_MESSAGE);
    txt_apellido.requestFocus();
    return;
       }
    if (txt_cedula.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar la Cédula", "Error", JOptionPane.ERROR_MESSAGE);
    txt_cedula.requestFocus();
    return;
       }
    if (txt_direccion.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar la Dirección", "Error", JOptionPane.ERROR_MESSAGE);
    txt_direccion.requestFocus();
    return;
       }
    if (txt_telefono.getText().trim().isEmpty()){
    JOptionPane.showMessageDialog(null, "Debe ingresar el Teléfono", "Error", JOptionPane.ERROR_MESSAGE);
    txt_telefono.requestFocus();
    return;
       }
    int mensaje = JOptionPane.showConfirmDialog(null, "¿Desea Grabar?", "Atención", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (mensaje == 0){
      DefaultTableModel tabla = (DefaultTableModel) tabla_contenido.getModel();
      if (variable_accion.equals("Nuevo")){
           tabla.addRow (new Object []{
           txt_codigo.getText(),
           txt_nombre.getText().toUpperCase(),
           txt_apellido.getText().toUpperCase(),
           txt_cedula.getText(),
           txt_direccion.getText().toUpperCase(),
           txt_telefono.getText(),
           cbox_ciudad.getSelectedItem(),
           cbox_pais.getSelectedItem(),
           rabtn_estado.isSelected()  
       });
      }
      

      if (variable_accion.equals("modificar")){
          tabla.removeRow(tabla_contenido.getSelectedRow());
           tabla.addRow (new Object []{
           txt_codigo.getText(),
           txt_nombre.getText().toUpperCase(),
           txt_apellido.getText().toUpperCase(),
           txt_cedula.getText(),
           txt_direccion.getText().toUpperCase(),
           txt_telefono.getText(),
           cbox_ciudad.getSelectedItem(),
           cbox_pais.getSelectedItem(),
           rabtn_estado.isSelected()  
       });
     }
    
      
    }
   
    
    }//GEN-LAST:event_btn_grabarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
int mensaje = JOptionPane.showConfirmDialog(this,"¿Desea salir?","Atencón",JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION){dispose();}
        new menu_principal().setVisible(true);

    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
   
        if(txt_codigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"DEBE SELECCIONAR UN REGISTRO","ATENCION!!!",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int mensaje = JOptionPane.showConfirmDialog(null,"¿DESEA ELIMINAR EL REGISTRO SELECCIONADO?", "ATENCION!!!", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (mensaje==0){
            DefaultTableModel tab = (DefaultTableModel)tabla_contenido.getModel();
                    tab.removeRow(tabla_contenido.getSelectedRow());
            btn_cancelar.doClick();
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscripcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_grabar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cbox_ciudad;
    private javax.swing.JComboBox<String> cbox_pais;
    private javax.swing.JLabel etiq_apellido;
    private javax.swing.JLabel etiq_cedula;
    private javax.swing.JLabel etiq_ciudad;
    private javax.swing.JLabel etiq_codigo;
    private javax.swing.JLabel etiq_direccion;
    private javax.swing.JLabel etiq_estado;
    private javax.swing.JLabel etiq_nombre;
    private javax.swing.JLabel etiq_pais;
    private javax.swing.JLabel etiq_telefono;
    private javax.swing.JLabel etiq_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcmouse_logo;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel panel_titulo;
    private javax.swing.JRadioButton rabtn_estado;
    private javax.swing.JTable tabla_contenido;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private void deshabilitar_botones() {
    btn_nuevo.setEnabled(true);
    btn_modificar.setEnabled(true);
    btn_eliminar.setEnabled(true);
    btn_grabar.setEnabled(true);
    btn_cancelar.setEnabled(true);
    btn_salir.setEnabled(true);
    }
}
